### ISSUE TITLE
Unable to  Unschedule

### ISSUE THREAD

**Issue by lgoehrs** [jamesmh/coravelpro#22]
When trying to unschedule from the web interface, we have the following error:

Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: Error: An unhandled exception has occurred while executing the request.

System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<!0> Microsoft.EntityFrameworkCore.DbSet`1.FindAsync(System.Object[])'.
   at Coravel.Pro.Features.Scheduling.UseCases.UnScheduleJobCommand.UnScheduleJob(Int32 id)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Coravel.Pro.Features.Scheduling.UseCases.UnScheduleJobCommand.UnScheduleJob(Int32 id)
   at Coravel.Pro.Coravel.Pages.SchedulingModel.OnPostUnschedule(UnscheduleJobRequest model)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by jamesmh** [comment]
What version of Coravel Pro are you using? What version of .NET Core?

Is the database only in use by one application or multiple?

**Comment by jamesmh** [comment]
Just saw your other issue: again, it could be due to .NET Core 3.0

Is there any way to try using .NET Core 2.2 as a test?

In any case, Coravel Pro doesn't "really" support .NET Core 3.0 right now due to breaking changes made between 2.2 and 3.0.

**Comment by jamesmh** [comment]
Going to close this. Support for 3.0+ is available now #24 if that helps.
