### ISSUE TITLE
How to create tables in database using script

### ISSUE THREAD

**Issue by SuheylZ** [jamesmh/coravelpro#25]
I'm using Coravel pro trial and had a hard time with the DbContext. 

We do not use migrations and use only database first approach. Whenever I run the app the app crashes at 

` app.UseCoravelPro();`

and here is my sql script:
```
create table dbo.CoravelJobHistory(
	Id int identity primary key,
	StartedAt datetime null, 
	EndedAt  datetime null , 
	TypeFullPath nvarchar(max), 
	DisplayName  nvarchar(max), 
	Failed 	    bit, 
	ErrorMessage nvarchar(max), 
	StackTrace   nvarchar(max)
)
go

create table dbo.CoravelScheduledJob(
	Id int identity not null primary key,
	InvocableFullPath nvarchar(max),
	CronExpression	nvarchar(max),
	Frequency			nvarchar(max),
	Days				nvarchar(max),
	PreventOverlapping  bit,
	CreatedAt		datetime,
	Active				bit
)
go

create table dbo.CoravelScheduledJobHistory (
	Id int identity primary key,
	EndedAt datetime null,
	TypeFullPath nvarchar(max),
	DisplayName nvarchar(max),
	Failed bit,
	ErrorMessage nvarchar(max),
	StackTrace nvarchar(max)
)
go
```
the exception that is thrown at the UseCoravelPro() says:

System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Invalid object name 'Coravel_JobHistory'.
  Source=Core .Net SqlClient Data Provider
  StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Coravel.Pro.Features.Jobs.UseCases.MarkJobsKilledByTerminatedProcessCommand.Invoke()
   at Coravel.Pro.ServiceRegistration.MarkJobsTerminatedByPreviouslyKilledProcess(IApplicationBuilder app)
   at Coravel.Pro.ServiceRegistration.UseCoravelPro(IApplicationBuilder app)
   at NQ.Jobs.CoravelStartup.Configure(IApplicationBuilder app) in D:\Projects\Quantum\source\API\NQ.Jobs\CoravelStartup.cs:line 26
   at NQ.Api.Framework.Startup.Microsoft.AspNetCore.Hosting.IStartup.Configure(IApplicationBuilder app) in D:\Projects\Quantum\source\API\NQ.Platform\NQ.API\Framework\Startup.cs:line 141
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

  This exception was originally thrown at this call stack:
	System.Data.SqlClient.SqlConnection.OnError(System.Data.SqlClient.SqlException, bool, System.Action<System.Action>)
	System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(System.Data.SqlClient.TdsParserStateObject, bool, bool)
	System.Data.SqlClient.TdsParser.TryRun(System.Data.SqlClient.RunBehavior, System.Data.SqlClient.SqlCommand, System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.BulkCopySimpleResultSet, System.Data.SqlClient.TdsParserStateObject, out bool)
	System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
	System.Data.SqlClient.SqlDataReader.MetaData.get()
	System.Data.SqlClient.SqlCommand.FinishExecuteReader(System.Data.SqlClient.SqlDataReader, System.Data.SqlClient.RunBehavior, string)
	System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(System.Data.CommandBehavior, System.Data.SqlClient.RunBehavior, bool, bool, int, out System.Threading.Tasks.Task, bool, System.Data.SqlClient.SqlDataReader)
	System.Data.SqlClient.SqlCommand.ExecuteReader(System.Data.CommandBehavior)
	Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(Microsoft.EntityFrameworkCore.Storage.IRelationalConnection, Microsoft.EntityFrameworkCore.Diagnostics.DbCommandMethod, System.Collections.Generic.IReadOnlyDictionary<string, object>)
	Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(Microsoft.EntityFrameworkCore.Storage.IRelationalConnection, System.Collections.Generic.IReadOnlyDictionary<string, object>)
    ...
    [Call Stack Truncated]

What am I missing in the DB Script?

**Comment by jamesmh** [comment]
Thanks for reaching out.

This should work, but keep in mind that future migrations/features may break your schema (so you'll manually have to update them vs. using the EF migrations). You already know that though 😊

Here are the scripts generated from SQL management studio:

```sql
USE [YOURDATABASEINSTANCE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Coravel_JobHistory](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[StartedAt] [datetime2](7) NULL,
	[EndedAt] [datetime2](7) NULL,
	[TypeFullPath] [nvarchar](max) NULL,
	[DisplayName] [nvarchar](max) NULL,
	[Failed] [bit] NOT NULL,
	[ErrorMessage] [nvarchar](max) NULL,
	[StackTrace] [nvarchar](max) NULL,
 CONSTRAINT [PK_Coravel_JobHistory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```

```sql
USE [YOURDATABASEINSTANCE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Coravel_ScheduledJobHistory](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[EndedAt] [DATETIME2](7) NULL,
	[TypeFullPath] [NVARCHAR](MAX) NULL,
	[DisplayName] [NVARCHAR](MAX) NULL,
	[Failed] [BIT] NOT NULL,
	[ErrorMessage] [NVARCHAR](MAX) NULL,
	[StackTrace] [NVARCHAR](MAX) NULL,
 CONSTRAINT [PK_Coravel_ScheduledJobHistory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```

```sql
USE [YOURDATABASEINSTANCE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Coravel_ScheduledJobs](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[InvocableFullPath] [NVARCHAR](MAX) NULL,
	[CronExpression] [NVARCHAR](MAX) NULL,
	[Frequency] [NVARCHAR](MAX) NULL,
	[Days] [NVARCHAR](MAX) NULL,
	[PreventOverlapping] [BIT] NOT NULL,
	[CreatedAt] [DATETIME2](7) NOT NULL,
	[Active] [BIT] NOT NULL,
 CONSTRAINT [PK_Coravel_ScheduledJobs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```

**Comment by SuheylZ** [comment]
yup it works but I have posted another issue.

**Comment by lookingcloudy** [comment]
We use fluent migrator, not EF migrations.  Would be good to post these and any future changes as part of the documentation for Pro.

**Comment by jamesmh** [comment]
Updates are sent out via email (mostly commercial users). You can sign up via pro.coravel.net.

But yes, would be helpful to put those somewhere 😊.

Might include a section for that in the docs 👍
