### ISSUE TITLE
Cron expression 'N/A' is malformed.

### ISSUE THREAD

**Issue by DanElliott** [jamesmh/coravelpro#36]
Using `3.0.0-preview2`, I get the following exception when attempting to schedule a job:

```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while
  executing the request.

System.Exception: Cron expression 'N/A' is malformed.
   at Coravel.Scheduling.Schedule.Cron.CronExpression..ctor(String expression)
   at Coravel.Pro.Features.Scheduling.UseCases.PersistNewScheduledJobCommand.VerifyCronExpression(String cronExpression)
   at Coravel.Pro.Features.Scheduling.UseCases.PersistNewScheduledJobCommand.Save(String typeFullName, IEnumerable`1
      allowedDays, Boolean preventOverlapping, String frequency, String timeZoneString, String specifiedCronExpress)
   at Coravel.Pro.Coravel.Pages.SchedulingModel.OnPostScheduleJob(ScheduleJobRequest model)
```

Which resulted in the following prompt in the upper right corner:

![Whoops!](https://user-images.githubusercontent.com/1487149/91460619-04961e80-e856-11ea-9e4b-3efae7801e5e.png)

The follow is a sample setup to reproduce, full project [here](https://github.com/DanElliott/coravel-pro-issue).

```csharp
namespace Sample
{
    using Coravel.Invocable;
    using Coravel.Pro;
    using Coravel.Pro.EntityFramework;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Hosting;
    using System;
    using System.Threading.Tasks;

    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }

    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ApplicationDbContext>(options => options.UseInMemoryDatabase(databaseName: "JobBoard"));

            services.AddRazorPages().AddNewtonsoftJson();

            services.AddCoravelPro(typeof(ApplicationDbContext));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ApplicationDbContext context)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            context.Database.EnsureCreated();

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapGet("/", async context =>
                {
                    await Task.Run(() => context.Response.Redirect(location: @"/Coravel/Scheduling", permanent: true));
                });
            });

            app.UseCoravelPro();
        }
    }

    public class ApplicationDbContext : DbContext, ICoravelProDbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        { }

        public DbSet<CoravelJobHistory> Coravel_JobHistory { get; set; }
        public DbSet<CoravelScheduledJob> Coravel_ScheduledJobs { get; set; }
        public DbSet<CoravelScheduledJobHistory> Coravel_ScheduledJobHistory { get; set; }
    }

    public class MyFirstInvocable : IInvocable
    {
        public Task Invoke()
        {
            Console.WriteLine("This is my first invocable!");
            return Task.CompletedTask;
        }
    }
}
```

The workaround is to use a cron expression instead of the menu options.

**Comment by jamesmh** [comment]
Thanks Dan, will take a look :)

**Comment by jamesmh** [comment]
Version 3.0.0-preview3 should be available soon. Let me know how that works out 👍

Thanks for the awesome sample project too - makes things sooo much easier for me 😎
