### ISSUE TITLE
 RemoveCoravelProHistoryDataAfter30Days causing efcore error

### ISSUE THREAD

**Issue by bradruga** [jamesmh/coravelpro#50]
My company has been using coravel pro for a while now and we love the product!

We have an exception that occurs repeatedly at 0:00 UTC.  The error is occurring while running the RemoveCoravelProHistoryDataAfter30Days invocable which runs 2 efcore queries asynchronously.  It hasn't thrown an exception every single day but does fairly frequently (10 out of the last 30 days).

Error Message:

> A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.

Stack Trace:
```
 at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Coravel.Pro.EntityFramework.Invocables.RemoveCoravelProHistoryDataAfter30Days.Invoke()
   at Coravel.Scheduling.Schedule.Event.ScheduledEvent.InvokeScheduledEvent(CancellationToken cancellationToken) in C:\Users\james\code\github\coravel\Src\Coravel\Scheduling\Schedule\Event\ScheduledEvent.cs:line 129
   at Coravel.Scheduling.Schedule.Scheduler.<>c__DisplayClass28_0.<<InvokeEvent>g__Invoke|0>d.MoveNext() in C:\Users\james\code\github\coravel\Src\Coravel\Scheduling\Schedule\Scheduler.cs:line 165
--- End of stack trace from previous location ---
   at Coravel.Scheduling.Schedule.Scheduler.InvokeEvent(ScheduledEvent scheduledEvent) in C:\Users\james\code\github\coravel\Src\Coravel\Scheduling\Schedule\Scheduler.cs:line 196
```

```
public async Task Invoke()
{
  DateTimeOffset thirtyDaysAgo = DateTimeOffset.UtcNow.AddDays(-30.0);
  Task<List<CoravelJobHistory>> oldHistory = this._db.Coravel_JobHistory.Where<CoravelJobHistory>((Expression<Func<CoravelJobHistory, bool>>) (h => h.EndedAt != new DateTime?() && (DateTimeOffset?) h.EndedAt < (DateTimeOffset?) thirtyDaysAgo)).ToListAsync<CoravelJobHistory>();
  Task<List<CoravelScheduledJobHistory>> oldScheduleHistory = this._db.Coravel_ScheduledJobHistory.Where<CoravelScheduledJobHistory>((Expression<Func<CoravelScheduledJobHistory, bool>>) (h => h.EndedAt != new DateTime?() && (DateTimeOffset?) h.EndedAt < (DateTimeOffset?) thirtyDaysAgo)).ToListAsync<CoravelScheduledJobHistory>();
  await Task.WhenAll((Task) oldHistory, (Task) oldScheduleHistory);
  DbSet<CoravelJobHistory> dbSet1 = this._db.Coravel_JobHistory;
  dbSet1.RemoveRange((IEnumerable<CoravelJobHistory>) await oldHistory);
  dbSet1 = (DbSet<CoravelJobHistory>) null;
  DbSet<CoravelScheduledJobHistory> dbSet2 = this._db.Coravel_ScheduledJobHistory;
  dbSet2.RemoveRange((IEnumerable<CoravelScheduledJobHistory>) await oldScheduleHistory);
  dbSet2 = (DbSet<CoravelScheduledJobHistory>) null;
  int num = await (this._db as DbContext).SaveChangesAsync();
  oldHistory = (Task<List<CoravelJobHistory>>) null;
  oldScheduleHistory = (Task<List<CoravelScheduledJobHistory>>) null;
}
```

When I run the following code from the method in LinqPad it throws and exception every time:
```
DateTimeOffset thirtyDaysAgo = DateTimeOffset.UtcNow.AddDays(-30.0);
Task<List<CoravelJobHistory>> oldHistory = Coravel_JobHistory.Where<CoravelJobHistory>((Expression<Func<CoravelJobHistory, bool>>)(h => h.EndedAt != new DateTime?() && (DateTimeOffset?)h.EndedAt < (DateTimeOffset?)thirtyDaysAgo)).ToListAsync<CoravelJobHistory>();
Task<List<CoravelScheduledJobHistory>> oldScheduleHistory = Coravel_ScheduledJobHistory.Where<CoravelScheduledJobHistory>((Expression<Func<CoravelScheduledJobHistory, bool>>)(h => h.EndedAt != new DateTime?() && (DateTimeOffset?)h.EndedAt < (DateTimeOffset?)thirtyDaysAgo)).ToListAsync<CoravelScheduledJobHistory>();
await Task.WhenAll((Task) oldHistory, (Task) oldScheduleHistory);
```

Could you await each task individually?

Thanks!

**Comment by jamesmh** [comment]
Thanks for this. Looking to address this soon. Which version are you using? Thanks 🙂

**Comment by bradruga** [comment]
We're using Coravel version 4.2.1 and Coravel.Pro version 5.1.2.

Checking that made me realize that you have a newer version available for Coravel.Pro.  We'll upgrade to that and see if it helps.  I guess you'll know if that would affect this.

**Comment by jamesmh** [comment]
Try the newest version of Coravel Pro - 5.2.2. Should be fixed 👍 Will close the issue, but let me know if something (bad) comes up!

**Comment by bradruga** [comment]
Thank you!
