### ISSUE TITLE
CoravelPro fails after dotnet 8 migration

### ISSUE THREAD

**Issue by henryezeanya** [jamesmh/coravelpro#51]
After migrating to dotnet 8, I'm unable to start my asp.net core application, because the app.UseCoravelPro() keeps failing and throwing the following exception:

Exception
Message
Unable to load one or more of the requested types.
Could not load type 'SqlGuidCaster' from assembly 'Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.

Stack Trace
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Coravel.Pro.Features.Jobs.Services.InvocablesCollectionService.AddInvocablesFromAssembly(Assembly assembly)
   at Coravel.Pro.ServiceRegistration.AssignAllRegisteredJobs(IApplicationBuilder app)
   at Coravel.Pro.ServiceRegistration.UseCoravelPro(IApplicationBuilder app)
   at Program.<Main>$(String[] args) in C:\Engineering\DevCodes\OditorAppService\src\Api\src\Program.cs:line 221

**Comment by jamesmh** [comment]
This is not an issue with Coravel Pro, but with EF Core / .NET 8.

Here's a GitHub issue for reference -> https://github.com/dotnet/SqlClient/issues/1930

Try upgrading to a newer version of .NET 8?

**Comment by falvarez1** [comment]
Updating the `Microsoft.Data.SqlClient` to version 5.2.0-preview5.24024.3 seems to fix this, it's included in the [upcoming 5.2.0 release ](https://github.com/dotnet/SqlClient/milestone/60)
