### ISSUE TITLE
I have "System.NullReferenceException" in app.UseCoravelPro(); 

### ISSUE THREAD

**Issue by tolbxela** [jamesmh/coravelpro#9]
<h1>An error occurred while starting the application.</h1>
            <div class="titleerror">NullReferenceException: Object reference not set to an instance of an object.</div>
                <p class="location">Coravel.Pro.Features.Jobs.UseCases.MarkJobsKilledByTerminatedProcessCommand.Invoke()</p>

```
Coravel.Pro.Features.Jobs.UseCases.MarkJobsKilledByTerminatedProcessCommand.Invoke()
Coravel.Pro.ServiceRegistration.MarkJobsTerminatedByPreviouslyKilledProcess(IApplicationBuilder app)
Coravel.Pro.ServiceRegistration.UseCoravelPro(IApplicationBuilder app)
CoravelTest.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in Startup.cs
+
            app.UseCoravelPro();
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter+<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```
:-(

**Comment by jamesmh** [comment]
What version of .NET Core and Coravel Pro are you using?

**Comment by jamesmh** [comment]
Did this work before? Or this is your first time trying it out?

**Comment by tolbxela** [comment]
I am trying to start the Pro version with .Net 2.2 at first time. It's not so easy peasy. :-)
The free version did work well after some small fixes.

**Comment by tolbxela** [comment]
.NET Core 4.6.27817.03 X64 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 2.2.0-rtm-35687    |    Microsoft Windows 10.0.17134  
---

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Coravel.Pro.Features.Jobs.UseCases.MarkJobsKilledByTerminatedProcessCommand.Invoke()
   at Coravel.Pro.ServiceRegistration.MarkJobsTerminatedByPreviouslyKilledProcess(IApplicationBuilder app)
   at Coravel.Pro.ServiceRegistration.UseCoravelPro(IApplicationBuilder app)
   at CoravelTest.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in c:\Users\xxxxxx\Development\Coravel.Pro\Startup.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

**Comment by tolbxela** [comment]
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Coravel.Pro" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.2.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.2.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="2.2.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.2.0" />
  </ItemGroup>

</Project>

```

**Comment by jamesmh** [comment]
Can you post your Startup.cs?

**Comment by tolbxela** [comment]
Sure

```
using Coravel.Pro;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace CoravelTest
{
    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=Coravel;Trusted_Connection=True;MultipleActiveResultSets=true")
                .EnableSensitiveDataLogging(true)
            );
            services.AddCoravelPro(typeof(ApplicationDbContext));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseCoravelPro();
        }
    }
}

```

**Comment by tolbxela** [comment]
And here is ApplicationDbContext

```
using Coravel.Pro.EntityFramework;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace CoravelTest
{
    public class ApplicationDbContext : IdentityDbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(
                    "Server=(localdb)\\mssqllocaldb;Database=Coravel;Trusted_Connection=True;MultipleActiveResultSets=true"
                );
            }
        }

        public DbSet<CoravelJobHistory> Coravel_JobHistory { get; set; }
        public DbSet<CoravelScheduledJob> Coravel_ScheduledJobs { get; set; }
        public DbSet<CoravelScheduledJobHistory> Coravel_ScheduledJobHistory { get; set; }
    }
}

```

**Comment by tolbxela** [comment]
The EF migration was also done

**Comment by tolbxela** [comment]
Here is the project: https://github.com/tolbxela/Coravel.Pro.Test

**Comment by jamesmh** [comment]
How did you create your project? using `dotnet new`? 

It looks like you're missing a lot of MVC specific stuff (which is required).

You can try adding `services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);` to `ConfigureServices` as a start (before calling `AddCoravePro()`. If it does fix this issue I would still expect more issues since there's no way to Coravel to hook into the MVC framework.

If you try creating a project using `dotnet new mvc --auth identity` and then just copy the code you need from your project over then it ay solve this issue (and other ones that haven't appeared yet)

**Comment by tolbxela** [comment]
I did it and it have not worked.

https://github.com/tolbxela/Coravel.Pro.Test/commit/a794005e2e236926c93b2b99c20fb9659dc83cb9

```
Exception:
   at Coravel.Pro.Features.Jobs.UseCases.MarkJobsKilledByTerminatedProcessCommand.Invoke()
   at Coravel.Pro.ServiceRegistration.MarkJobsTerminatedByPreviouslyKilledProcess(IApplicationBuilder app)
   at Coravel.Pro.ServiceRegistration.UseCoravelPro(IApplicationBuilder app)
   at New.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in c:\Users\xxxxxxx\Development\New\Startup.cs:line 64
```

**Comment by jamesmh** [comment]
K I think I see the problem.

Follow the steps here in the documentation:

https://www.docs.pro.coravel.net/Installation/#basic-configuration

Looks like you're missing an interface on the ApplicationDbContext. Let me know if that works.

**Comment by tolbxela** [comment]
Yes, off course.  I have added ICoravelProDbContext to ApplicationDbContext and now it works well.
And it looks very good! Nice work! 👍

**Comment by jamesmh** [comment]
Great! 🤜🤛

**Comment by tolbxela** [comment]
I guess, it would be great to simplify the start with CoravelPro by creating a sample project. ;-)
